// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnetapp.Data;

#nullable disable

namespace dotnetapp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240627053352_asdfg")]
    partial class asdfg
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("dotnetapp.Models.Pet", b =>
                {
                    b.Property<int>("PetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PetID"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<bool>("Availability")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PetID");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            PetID = 1,
                            Age = 3,
                            Availability = true,
                            Name = "Buddy",
                            Type = "Dog"
                        },
                        new
                        {
                            PetID = 2,
                            Age = 2,
                            Availability = true,
                            Name = "Mittens",
                            Type = "Cat"
                        },
                        new
                        {
                            PetID = 3,
                            Age = 1,
                            Availability = true,
                            Name = "Tweety",
                            Type = "Bird"
                        },
                        new
                        {
                            PetID = 4,
                            Age = 1,
                            Availability = true,
                            Name = "Rocky",
                            Type = "Hamster"
                        },
                        new
                        {
                            PetID = 5,
                            Age = 2,
                            Availability = true,
                            Name = "Whiskers",
                            Type = "Rabbit"
                        });
                });

            modelBuilder.Entity("dotnetapp.Models.PetAdopter", b =>
                {
                    b.Property<int>("PetAdopterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PetAdopterID"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PetID")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PetAdopterID");

                    b.HasIndex("PetID");

                    b.ToTable("PetAdopters");
                });

            modelBuilder.Entity("dotnetapp.Models.PetAdopter", b =>
                {
                    b.HasOne("dotnetapp.Models.Pet", "Pet")
                        .WithMany("PetAdopters")
                        .HasForeignKey("PetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("dotnetapp.Models.Pet", b =>
                {
                    b.Navigation("PetAdopters");
                });
#pragma warning restore 612, 618
        }
    }
}
